node {
    
    stage('Preparacion') { 
        agent {
            docker { image 'openjdk:21-nanoserver' }
        }
        // Limpiamos nuestro workspace
        deleteDir()
        // Clonamos el proyecto
        sh 'git clone https://github.com/DataDog/vulnerable-java-application.git'

    }
    stage('Compilacion y Construimos') {
        agent {
            docker { image 'openjdk:21-nanoserver' }
        }        
        dir('vulnerable-java-application'){
            // Compilamos y contruimos el jar
            sh './gradlew clean build bootJar'
        }
    }
    stage('Despliegue') {
        agent {
            docker { image 'openjdk:21-nanoserver' }
        }
        dir('vulnerable-java-application'){
            // Matamos si existe una instancia en ejecucion
            sh 'pkill -f "build/libs/domain-tester-service-0.0.1-SNAPSHOT.jar" || true'
            // Se ejecuta la aplicacion
            sh 'nohup java -jar build/libs/domain-tester-service-0.0.1-SNAPSHOT.jar --server.port=9090 &'
        }
    }

    post {
        always {
            echo 'Pipeline finalizado. Verifique la aplicacion desplegada en http://localhost:9090'
        }
    }    
}