pipeline {
    agent any

    stages {
        stage('Analizando codigo') {         
            steps {
                sh '''
                    cd "${WORKSPACE}"
                    rm -rf vulnerable-java-application 
                    git clone https://github.com/DataDog/vulnerable-java-application.git
                    docker pull semgrep/semgrep
                    docker run --rm -v "$(pwd)/vulnerable-java-application:/src" semgrep/semgrep semgrep scan
                '''
            }
        }
    }
}       
/*
        stage('Compilacion y Construimos') {
            steps {
                sh 'cd vulnerable-java-application'
                sh './gradlew clean build bootJar'
            }
        }        

        stage('Despliegue') {
            agent {
                docker { image 'eclipse-temurin:21-jdk' }
            }
            dir('vulnerable-java-application'){
                // Matamos si existe una instancia en ejecucion
                sh 'pkill -f "build/libs/domain-tester-service-0.0.1-SNAPSHOT.jar" || true'
                // Se ejecuta la aplicacion
                sh 'nohup java -jar build/libs/domain-tester-service-0.0.1-SNAPSHOT.jar --server.port=9090 &'
            }
        }    
    }
}            
    */
